version: '3.4'

services:
  hotchocolategraphql:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CommandConStr=Data Source=sqlserver,1433;Database=CommandsDB;User ID=sa;Password=pa55w0rd!"
    ports:
      - "6969:80"
    depends_on:
      - sqlserver

  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pa55w0rd!
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
