version: '3.4'

services:
  hotchocolategraphql:
    image: ${DOCKER_REGISTRY-}hotchocolategraphql
    build:
      context: .
      dockerfile: HotChocolateGraphQL/Dockerfile
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

volumes:
  sqlvolume:
